### ISSUE TITLE
Nome da blockchain explorer errado na listagem.

### ISSUE THREAD

**Issue by Ronyell** [liftlearning/P2Pix-Front-End#27]
Nome da blockchain explorer errado na listagem.

Deve ficar assim:

Polygon: Polygonscan - https://mumbai.polygonscan.com/
Ethers: Etherscan - https://goerli.etherscan.io/

![image](https://user-images.githubusercontent.com/20937537/217102858-2f0591fa-ef9c-41c8-9ce1-048ac0b1c55f.png)

_Originally posted by @Ronyell in https://github.com/liftlearning/P2Pix-Front-End/pull/22#discussion_r1097989701_

**Comment by RcleydsonR** [comment]
Esse comportamento já foi consertado no PR: https://github.com/liftlearning/P2Pix-Front-End/pull/34
