### ISSUE TITLE
Esta mostrando o modal para o usuario web 

### ISSUE THREAD

**Issue by Ronyell** [liftlearning/P2Pix-Front-End#31]
![image](https://user-images.githubusercontent.com/20937537/217110026-c54943dd-e0c0-4dfa-84d9-e562cf231356.png)

**Comment by RcleydsonR** [comment]
Comportamento consertado na branch 'lock_redirection'.
Visualização da solução vide commit: acbef9c5569257331248d1831365ea7e25cfcfc2

**Comment by RcleydsonR** [comment]
Issue finalizada
