### ISSUE TITLE
Ajustar import dos componentes com alias

### ISSUE THREAD

**Issue by Ronyell** [liftlearning/P2Pix-Front-End#32]
No momento as importacoes estao sendo feitas por meio de path relativo.

Como esta:
```import SendNetwork from "../components/SellerSteps/SendNetwork.vue";```

Como deve ser:
```import SendNetwork from "@/components/SellerSteps/SendNetwork.vue";```

**Comment by RcleydsonR** [comment]
Issue finalizada
