### ISSUE TITLE
Adicionar loading ao trocar de block explorer

### ISSUE THREAD

**Issue by Ronyell** [liftlearning/P2Pix-Front-End#33]
Ao trocar de block explorer, imediatamente e atualizado o nome do block explorer, mas e necessario adicionar um loading para corrigir esse problema.

**Comment by RcleydsonR** [comment]
Task feita em 3c15b5a82eb9f62220a92fc1759b42d68ec39986 e f9d8f18589318a6f4039c32f9c98557592dbbd9e
