### ISSUE TITLE
Para usuarios sem saldo deve omitir o componente de withdraw na tela pos-compra e listar todas as transacoes do usuario

### ISSUE THREAD

**Issue by Ronyell** [liftlearning/P2Pix-Front-End#46]
Para usuarios sem saldo deve omitir o componente de withdraw na tela pos-compra 
Listar todas as transacoes no gerenciar transacoes (compra, venda, retirada e reserva)

**Comment by RcleydsonR** [comment]
Task feita em: 3c15b5a82eb9f62220a92fc1759b42d68ec39986
